# Generated by Django 5.2.6 on 2025-11-22 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='mascota',
            name='ubicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mascotas.ubicacion'),
        ),
    ]
