# Generated by Django 5.2.6 on 2025-11-22 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_ubicacion_mascota_ubicacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'verbose_name': 'Ubicación', 'verbose_name_plural': 'Ubicaciones'},
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='ciudad',
        ),
    ]
