# Generated by Django 5.2.6 on 2025-11-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_alter_ubicacion_options_remove_ubicacion_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='abreviatura',
            field=models.CharField(default='MX', max_length=10),
            preserve_default=False,
        ),
    ]
