# Generated by Django 5.2.6 on 2025-11-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0004_ubicacion_abreviatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='edad',
        ),
        migrations.AddField(
            model_name='mascota',
            name='edad_meses',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
