# Generated by Django 5.2.6 on 2025-11-22 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0005_remove_mascota_edad_mascota_edad_meses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mascotas.ubicacion'),
        ),
    ]
