# Generated by Django 4.2.26 on 2025-12-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0007_mascota_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('publicador', 'Publicador'), ('adoptante', 'Adoptante')], default='adoptante', max_length=20),
        ),
    ]
