# Generated by Django 4.2.27 on 2025-12-02 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mascotas', '0008_perfilusuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre de la Especie'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción Detallada'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='edad_meses',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Edad en Meses'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.especie', verbose_name='Especie'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='fecha_reporte',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Publicación'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(upload_to='mascotas/', verbose_name='Fotografía'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de la Mascota'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='publicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Publicado por'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], default='macho', max_length=10, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mascotas.ubicacion', verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='vacunado',
            field=models.BooleanField(default=False, verbose_name='¿Está Vacunado?'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Biografía'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('publicador', 'Publicador'), ('adoptante', 'Adoptante')], default='adoptante', max_length=20, verbose_name='Rol del Usuario'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfilusuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='abreviatura',
            field=models.CharField(max_length=10, verbose_name='Abreviatura'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='estado',
            field=models.CharField(max_length=30, verbose_name='Nombre del Estado'),
        ),
    ]
